version: '3.8'

services:
  db:
    image: postgres:14
    container_name: forum_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum_logs
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data